# Spring properties
spring:
  application:
     name: microservice-demo

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.50:1111/eureka/

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port
  